export { default as Banner } from './Banner/Banner';
export { default as Business } from './Business/Business';
export { default as Develop } from './Develop/Develop';
export { default as Info } from './Info/Info';
export { default as Pricing } from './Pricing/Pricing';
export { default as Slider } from './Slider/Slider';
export { default as Unlimited } from './Unlimited/Unlimited';
export { default as Trusted } from './Trusted/Trusted';
export { default as Plan } from './Plan/Plan';
